security:
    encoders:
        App\Users\Domain\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Users\Domain\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|uploads)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Shared\Infrastructure\Security\Authenticator\LoginFormAuthenticator
                    - App\Shared\Infrastructure\Security\Authenticator\ApiTokenAuthenticator
                entry_point: App\Shared\Infrastructure\Security\Authenticator\LoginFormAuthenticator
            logout:
                path: app_logout

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
