monolog:
    channels: ['email_confirm']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # Логирование событий подтверждения почты
        email_confirm:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/email_confirm.log"
            level: debug
            channels: ['email_confirm']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
