monolog:
    channels: ['email_confirm', 'module']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # Логирование событий подтверждения почты
        email_confirm:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/email_confirm.log"
            level: debug
            channels: ['email_confirm']
        # Логирование ошибок связанных с функционалом модулей
        module:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/module.log"
            level: error
            channels: ['module']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
