version: "3.8"

networks:
  blablaarticle-net:

services:
  php-8.1-fpm:
    container_name: php-8.1-blablaarticle
    build:
      # Указываем, где находится проект, к которому применяется сборка
      context: ./../
      dockerfile: ./deployment/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=blablaarticle"
    volumes:
      - ./../:/var/www/blablaarticle
    networks:
      - blablaarticle-net

  nginx:
    container_name: nginx-blablaarticle
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../:/var/www/blablaarticle:rw
    depends_on:
      - php-8.1-fpm
    networks:
      - blablaarticle-net

  postgres:
    container_name: blablaarticle-db
    build:
      # Где искать докерфайл
      context: ./postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - blablaarticle-net

  node:
    image: node:latest
    container_name: node
    volumes:
      - ../:/var/www/blablaarticle
    working_dir: /var/www/blablaarticle
    networks:
      - blablaarticle-net

volumes:
  db_data:
