parameters:
    # имя и email отправителя для рассылки с сайта
    sender.email: '%env(SENDER_EMAIL)%'
    sender.name: '%env(SENDER_NAME)%'
    # протокол и хост для перехода по ссылке указанной в письме рассылки
    router.request_context.scheme: '%env(SITE_BASE_SCHEME)%'
    router.request_context.host: '%env(SITE_BASE_HOST)%'
    # шаблоны email рассылок
    confirm_email.email.template: 'email/%env(CONFIRM_EMAIL_TEMPLATE)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    # Сервисы email рассылок
    app.mailer:
        namespace: App\Mailer\
        resource: '../src/Mailer/'
        tags: ['app_mailer']
    # Регистрация переменной $confirmEmailMailer как экземпляра класса ConfirmEmailMailer
    App\Mailer\BaseMailer $confirmEmailMailer: '@App\Mailer\ConfirmEmailMailer'

    # Сервисы подписчиков на события
    app.event_subscriber:
        namespace: App\EventSubscriber\
        resource: '../src/EventSubscriber/'
        tags: ['app_event_subscriber']

    app.mailer.confirm_email:
        class: App\Mailer\ConfirmEmailMailer

    # Сервисы генерации статьи
    app.article_generation_strategy:
        namespace: App\ArticleGeneration\Strategy\
        resource: '../src/ArticleGeneration/Strategy'
        tags: ['apps_article_generation_strategy']
    # Демо-стратегия генерации статьи
    app.article_demo_generation:
        class: App\ArticleGeneration\Strategy\DemoArticleGenerationStrategy

    # Сервис вставки продвигаемого слова
    app.promoted_word_inserter:
        class: App\ArticleGeneration\PromotedWordInserter

    Twig\Extension\StringLoaderExtension:
