# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # имя и email отправителя для рассылки с сайта
    sender.email: '%env(SENDER_EMAIL)%'
    sender.name: '%env(SENDER_NAME)%'
    # протокол и хост для перехода по ссылке указанной в письме рассылки
    router.request_context.scheme: '%env(SITE_BASE_SCHEME)%'
    router.request_context.host: '%env(SITE_BASE_HOST)%'
    # шаблоны email рассылок
    confirm_email.email.template: 'email/%env(CONFIRM_EMAIL_TEMPLATE)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    # Сервисы email рассылок
    app.mailer:
        namespace: App\Mailer\
        resource: '../src/Mailer/'
        tags: ['app_mailer']
    # Регистрация переменной $confirmEmailMailer как экземпляра класса ConfirmEmailMailer
    App\Mailer\BaseMailer $confirmEmailMailer: '@App\Mailer\ConfirmEmailMailer'

    # Сервисы подписчиков на события
    app.event_subscriber:
        namespace: App\EventSubscriber\
        resource: '../src/EventSubscriber/'
        tags: ['app_event_subscriber']
    # Подписчик на событие регистрации
    app.event_subscriber.user_registration_subscriber:
        class: App\EventSubscriber\UserRegisteredSubscriber
#        app.mailer.base $confirmEmailMailer: '@app.mailer.confirm_email'
#        arguments:
#            $confirmEmailMailer: '@app.mailer.base'

    app.mailer.confirm_email:
        class: App\Mailer\ConfirmEmailMailer


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
